service: product-service2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    PG_HOST: cloudx-aws.cwlxkclzz3mh.us-east-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: shop
    PG_USERNAME:
    PG_PASSWORD:
plugins:
  - serverless-esbuild
functions:
  getProductsList:
    handler: src/functions/getProductsList/handler.main
    events:
     - http:
        method: 'get'
        path: 'products'
        cors: true
  getProductById:
    handler: src/functions/getProductById/handler.main
    events:
     - http:
        method: 'get'
        path: 'products/{id}'
        cors: true
        request:
          parameters:
            paths:
              id: true
  createProduct:
    handler: src/functions/createProduct/handler.main
    events:
     - http:
        method: 'post'
        path: 'products'
        cors: true



